# Generated by Django 4.1.5 on 2023-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='images',
        ),
        migrations.AlterField(
            model_name='cuser',
            name='birthday',
            field=models.DateField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Мужчина', 'Женщина'), ('Другой', 'Другой')], default='Мужчина', max_length=15),
        ),
    ]
